name: pro_angler
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.2
  collection: ^1.17.0
  firebase: ^9.0.3
  firebase_auth: ^4.7.1
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.0
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/trophy.png
    - assets/images/teste.jpg
    - assets/images/distintivo.png
    
    #Conquistas
    - assets/images/conquistas/entusiasta.png
    - assets/images/conquistas/semrumo.png
    - assets/images/conquistas/trevo.png

    #Troféus
    - assets/images/trofeus/trofeu.png
    - assets/images/trofeus/peixaria.png
