// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL1Q7MXcTdQtxv7hPTJkrIpeqW2Rd3k8s',
    appId: '1:86510746527:web:a0d8f3ed5dc09cd19d5baa',
    messagingSenderId: '86510746527',
    projectId: 'proangler-e22d6',
    authDomain: 'proangler-e22d6.firebaseapp.com',
    storageBucket: 'proangler-e22d6.appspot.com',
    measurementId: 'G-GG099NXJEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0hiwOw7AKh0g4IK_A0BxCXMO-jgSVwU',
    appId: '1:86510746527:android:1719f18a7d913f5b9d5baa',
    messagingSenderId: '86510746527',
    projectId: 'proangler-e22d6',
    storageBucket: 'proangler-e22d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8hgGj3BrapLkbqFOtUuBTUuSNbMAIOWE',
    appId: '1:86510746527:ios:aafeb66b2c6610819d5baa',
    messagingSenderId: '86510746527',
    projectId: 'proangler-e22d6',
    storageBucket: 'proangler-e22d6.appspot.com',
    androidClientId: '86510746527-q2rhficnar3mm89apdd8amnb4j7i89is.apps.googleusercontent.com',
    iosClientId: '86510746527-luo9imioddt98goke46vc10v5uua6l5o.apps.googleusercontent.com',
    iosBundleId: 'com.tucuna.proangler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8hgGj3BrapLkbqFOtUuBTUuSNbMAIOWE',
    appId: '1:86510746527:ios:aafeb66b2c6610819d5baa',
    messagingSenderId: '86510746527',
    projectId: 'proangler-e22d6',
    storageBucket: 'proangler-e22d6.appspot.com',
    androidClientId: '86510746527-q2rhficnar3mm89apdd8amnb4j7i89is.apps.googleusercontent.com',
    iosClientId: '86510746527-luo9imioddt98goke46vc10v5uua6l5o.apps.googleusercontent.com',
    iosBundleId: 'com.tucuna.proangler',
  );
}
